User.destroy_all
Product.destroy_all
Review.destroy_all

Product.create(name: "Rainbow Bath Mat", price: 10, color: "Multi", category: "home", image: "https://s7d5.scene7.com/is/image/UrbanOutfitters/62970454_001_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=960", backimage:"https://s7d5.scene7.com/is/image/UrbanOutfitters/62970454_001_d?$medium$&fit=constrain&fmt=webp&hei=1046&qlt=80&wid=698", desc: "Channel rich color and dreamy vibes with this rainbow bath mat by Kip&Co. Shaped design made from a cotton tufted shag with a textural pile that’s so cushy underfoot.", subtype: "Bath")
Product.create(name: "Froggie Bath Mat", price: 10, color: "Multi", category: "home", image: "https://s7d5.scene7.com/is/image/UrbanOutfitters/64299340_095_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=960", backimage: "https://s7d5.scene7.com/is/image/UrbanOutfitters/64299340_095_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=960", desc: "Hop through your daily routines with this ultra-cute frog-shaped bath mat that turns your getting-ready space into its very own lily pad. Made from cotton terry that’s so cushy.", subtype: "Bath")
Product.create(name: "Yin Yang Mirror Set", price: 12, color: "Natural", category: "home", image: "https://s7d5.scene7.com/is/image/UrbanOutfitters/63371736_111_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=960" , backimage: "https://s7d5.scene7.com/is/image/UrbanOutfitters/63371736_111_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=960", desc: "Find balance with this two-piece mirror in a nestled yin yang silhouette", subtype: "Decor")
Product.create(name: "Willow USB Desk Lamp", price: 11, color: "Gold", category: "home", image: "https://s7d5.scene7.com/is/image/UrbanOutfitters/56958325_070_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=960", backimage: "https://s7d5.scene7.com/is/image/UrbanOutfitters/56958325_070_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=960", desc: "Metal desk lamp with built-in USB port, perfect for shining a light on your workspace with sleekly cool style. Plugs in to power on with inline rotary switch and USB port to charge up your tech.", subtype: "Lighting")
Product.create(name: "Eggcellent Day Mug", price: 8, color: "Purple", category: "home", image: "https://s7d5.scene7.com/is/image/UrbanOutfitters/63584965_053_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=960", backimage: "https://s7d5.scene7.com/is/image/UrbanOutfitters/63584965_053_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=960", desc: "Have an eggcellent day with this ceramic mug with an eggy graphic.", subtype: "Living")
Product.create(name: "Sugarcane Tartan Queen Size Duvet Cover", price: 80, color: "Multi", category: "home", image: "https://s7d5.scene7.com/is/image/UrbanOutfitters/62853858_079_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=960", backimage: "https://s7d5.scene7.com/is/image/UrbanOutfitters/62853858_079_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=960", desc: "Cozy and colorful cottage-ready vibes with this inviting tartan duvet cover by Kip&Co. Crafted from French flax linen, it features a hidden-button closure along the edge to easily remove on laundry day. Pillowcases and duvet insert sold separately.", subtype: "Bedding")
Product.create(name: "Alana Large Bookshelf", price: 75, color: "Black", category: "home", image: "https://s7d5.scene7.com/is/image/UrbanOutfitters/63787030_001_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=960", backimage: "https://s7d5.scene7.com/is/image/UrbanOutfitters/63787030_001_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=960", desc: "Powder-coated metal bookshelf with a modular look inspired by ‘60s décor. Featuring a variety of compartments with curving edges to store books, records set at a slant, trinkets and more, just the way you like. No two displays will ever be the same! Standing construction features looped legs. Assembly required.", subtype: "Furniture")
Product.create(name: "Cora Floor Mirror", price: 45, color: "Black", category: "home", image: "https://s7d5.scene7.com/is/image/UrbanOutfitters/62970454_001_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=960", backimage: "https://s7d5.scene7.com/is/image/UrbanOutfitters/62970454_001_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=960", desc: "Simply luxe floor mirror featuring an arching metal frame in a powder-coated finish designed to sit on the floor and lean against your wall while providing a full-length view that lets you catch every angle of your look. Available exclusively at Urban Outfitters.", subtype: "Furniture")
Product.create(name: "My Chemical Romance Look Alive Sunshine Flag Tapestry", price: 35, color: "Black", category: "home", image: "https://s7d5.scene7.com/is/image/UrbanOutfitters/65794661_001_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=960", backimage: "https://s7d5.scene7.com/is/image/UrbanOutfitters/65794661_001_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=960", desc: "Wool My Chemical Romance tapestry from the experts at Oxford Pennant. About Oxford Pennant: Oxford Pennant designs and manufactures vintage-look felt pennants, flags and banners inspired by the classic sports traditions of America. Founded in 2013 and located in Buffalo, New York, they design products that will inspire you to Celebrate Everything, from your hometown to your favorite band.", subtype: "Decor")
Product.create(name: "3x5 Miriam Printed Chenille Rug", price: 80, color: "Multi", category: "home", image: "https://s7d5.scene7.com/is/image/UrbanOutfitters/64203318_061_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=1080", backimage: "https://s7d5.scene7.com/is/image/UrbanOutfitters/64203318_061_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=1080", desc: "Inspired by vintage motifs, this soft chenille rug is topped with an intricate geometric featuring bordered details, swirls and scrolling accents, trimmed with fringed edges. Recommended for use with a rug pad - sold separately.", subtype: "Living")
Product.create(name: "Yin Yang Bookend Set", price: 18, color: "Multi", category: "home", image: "https://s7d5.scene7.com/is/image/UrbanOutfitters/62879333_095_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=1080", backimage: "https://s7d5.scene7.com/is/image/UrbanOutfitters/62879333_095_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=1080", desc: "Bring balanced energy and nostalgic aesthetics to your display with this duo set of ceramic bookends topped with glazed details to create a yin yang motif.", subtype: "Decor")
Product.create(name: "Spider House Plant in Ceramic Thankful Planter", price: 35, color: "White", category: "home", image:"https://s7d5.scene7.com/is/image/UrbanOutfitters/66667817_014_m?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=1080", backimage: "https://s7d5.scene7.com/is/image/UrbanOutfitters/66667817_014_m3?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=1080", desc: "The Chlorophytum comosum 'bonnie' or 'Bonnie Curly Spider Plant' is one of the most popular, adaptable, and easiest to grow of all hanging houseplants. Although spider plants prefer bright light, they tend to scorch in direct sunlight. These plants have tremendous air purifying qualities, and have the ability to remove volatile organic pollutants. This plant comes in a grow pot in a ceramic “thankful” planter.", subtype: "Living")
Product.create(name: "Cloud Removable Wallpaper", price: 45, color: "Blue", category: "home", image: "https://s7d5.scene7.com/is/image/UrbanOutfitters/66653338_040_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=1080", backimage:"https://s7d5.scene7.com/is/image/UrbanOutfitters/66653338_040_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=1080", desc: "Easily removable stick-on wallpaper. Cut in panels you can use to accent one wall or tile all over your room, in a matte finish with vibrant, water-based, non-toxic inks. Comes with one strip of wallpaper in an allover repeating pattern - choose from three different sizes to best suit your space.", subtype: "Decor")
Product.create(name: "Sarah Eisenlohr Dimensions Art Print", price: 65, color: "Natural", category: "home", image: "https://s7d5.scene7.com/is/image/UrbanOutfitters/65667859_014_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=1080", backimage:"https://s7d5.scene7.com/is/image/UrbanOutfitters/65667859_014_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=1080", desc: "Find your way past the rainbow with this collaged art print by Sarah Eisenlohr. Printed on archival paper made from cotton pressed in Italian mills, this high-quality art print is available in sizes and frames just right for your space. First select your frame (or go frameless), then select your size.", subtype: "Decor")
Product.create(name: "Butterfly Queen Size Duvet Set", price: 80, color: "Black", category: "home", image: "https://s7d5.scene7.com/is/image/UrbanOutfitters/60190170_001_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=1080", backimage: "https://s7d5.scene7.com/is/image/UrbanOutfitters/60190170_001_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=1080", desc: "Coordinate your bedding to flit away on sweet dreams with this duvet set featuring butterflies fluttering across the surface. Comes with a duvet cover, pillowcases and a tote bag to hold it all. Made in a soft weave, the pillowcases feature side slits and the duvet cover features a hidden-button closure along the edge and ties at the inner corners, to easily remove it all and toss in the wash. Pillows and duvet insert sold separately. Meets OEKO-TEX® Standard 100 guidelines which independently test each component for harmful substances for textiles you can trust.", subtype: "Bedding")
Product.create(name: "Full Moon Mountain Art Print", price: 45, color: "Natural", category: "home", image: "https://s7d5.scene7.com/is/image/UrbanOutfitters/65043663_014_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=1080", backimage: "https://s7d5.scene7.com/is/image/UrbanOutfitters/65043663_014_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=1080", desc: "Manifest your dream view with this art print by sandrapoliakov, featuring a figure looking out at a moonlit mountain landscape. Printed on archival paper made from cotton pressed in Italian mills, this high-quality art print is available in sizes and frames just right for your space. First select your frame (or go frameless), then select your size.", subtype: "Decor")
Product.create(name: "Pothos Ivy Houseplant in Ceramic Planter", price: 35, color: "White", category: "home", image: "https://s7d5.scene7.com/is/image/UrbanOutfitters/63107007_010_m?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=1080", backimage: "https://s7d5.scene7.com/is/image/UrbanOutfitters/63107007_010_m3?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=1080", desc: "The “Golden Pothos” or “Devil’s Ivy” is one of the best beginner houseplants to start with. The Pothos does require more frequent waterings, however, it can sustain low-moderate light conditions. This plant is a great air purifier as it can cleanse spaces of volatile organic pollutants. This plant comes with a minimalistic white planter.", subtype: "Living")
Product.create(name: "Steel Bathroom Wall Shelf", price: 39, color: "Silver", category: "home", image: "https://s7d5.scene7.com/is/image/UrbanOutfitters/65301061_007_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=1080", backimage: "https://s7d5.scene7.com/is/image/UrbanOutfitters/65301061_007_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=1080", desc: "Slatted steel wall shelf, perfect for storing fragrance, toiletries and towels in just the right place with sleekly modern style. Mounts to wall; hanging hardware included.", subtype: "Decor")
Product.create(name: "Low Storage Shelf", price: 125, color: "Brown", category: "home", image: "https://s7d5.scene7.com/is/image/UrbanOutfitters/62974902_020_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=1080", backimage: "https://s7d5.scene7.com/is/image/UrbanOutfitters/62974902_020_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=1080", desc: "Two-tier mango wood storage shelf from our Urban Outfitters-exclusive Huron collection that takes its cues from topographical layers, curves and patterns. Featuring two fixed-position shelves with waving edges that undulate to create irregular patterns that make for a standout display you can customize just how you like. Supported by framed sides. Made from natural mango wood, the storage shelf you receive may vary slightly in tone, finish and appearance from what's pictured here. This custom furniture piece will be made to order just for you. Two people recommended for assembly.", subtype: "Furniture")
Product.create(name: "Smoko Frog Light", price: 15, color: "Green", category: "home", image: "https://s7d5.scene7.com/is/image/UrbanOutfitters/63639215_030_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=1080", backimage: "https://s7d5.scene7.com/is/image/UrbanOutfitters/63639215_030_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=1080", desc: "Turn your space into a lily pad with this ultra-cute frog-shaped light by Smoko. Small design features a glowing finish, perfect for keeping on your nightstand or bookshelf. With one hour auto-off.", subtype: "Decor")
Product.create(name: "Metal Over-The-Door-Shoe Rack", price: 40, color: "White", category: "home", image: "https://images.urbndata.com/is/image/UrbanOutfitters/48789291_010_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=1314", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/48789291_010_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc: "Maximize your storage space with this over-the-door shoe rack. Slim metal rack with space for 18 pairs of shoes, with 3 pairs on each tier. Looped wire bars are shaped to hold shoes without damaging. Hooks over door (hardware included).", subtype: "Furniture")
Product.create(name: "Heartbeat Makeup Vanity Mirror", price: 13, color: "Green", category: "home", image: "https://images.urbndata.com/is/image/UrbanOutfitters/52582137_237_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=960", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/52582137_237_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=960", desc: "Show your shelf some love with this standing LED mirror in the shape of a heart. Features a catch-all tray base to store your favorite jewelry, makeup and skincare.", subtype: "Living")
Product.create(name: "Butterfly Shower Curtain", price: 28, color: "Multi", category: "home", image: "https://images.urbndata.com/is/image/UrbanOutfitters/64299829_004_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=960", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/64299829_004_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=960", desc: "Flutter through your daily routine with this cotton shower curtain, topped with a butterfly print that’s so boho-cool. Complete with perforations along the upper edge for easy setup.", subtype: "Bath")
Product.create(name: "Remote Controlled Corner Floor Lamp", price: 35, color: "White", category: "home", image: "https://images.urbndata.com/is/image/UrbanOutfitters/64620180_010_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=960", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/64620180_010_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=960", desc: "Set the coolest mood in your space with this color-changing corner-fit floor lamp by Brilliant Ideas. Designed to nestle into corners and subtly diffuse colorful light across your walls. Remote controlled. Operates via USB cable.", subtype: "Lighting")
Product.create(name: "Mug Storage Tree", price: 18, color: "Black", category: "home", image: "https://images.urbndata.com/is/image/UrbanOutfitters/51717288_001_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=960", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/51717288_001_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=960", desc: "Store mugs + more on this standing rack, featuring a trio of dowel arms set on a round base. Keeps your mugs on display in just the right place", subtype: "Decor")
Product.create(name:"Yogi Love Seat",price: 800, color: "White", category: "home", image: "https://images.urbndata.com/is/image/UrbanOutfitters/63139729_011_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=960", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/63139729_011_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=960", desc: "Inviting upholstered love seat that captures an approachable, modern look with curving lines all over and a wooden block base. Padded construction is topped with a single seat cushion that’s equal parts chic and comfy. Two people recommended for assembly", subtype: "Furniture")
Product.create(name: "Modern Wall Multi-Hook",price: 48, color: "Brown", category: "home", image: "https://images.urbndata.com/is/image/UrbanOutfitters/38379590_020_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=540", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/38379590_020_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=540", desc: "Mid-century modern-inspired wall hook, crafted from durable Mango wood. Complete with 5 hooks for storing bags, jackets, accessories and more! Hardware not included.", subtype: "Decor")
Product.create(name: "Charlotte Vanity",price: 125, color: "Gold", category: "home", image: "https://images.urbndata.com/is/image/UrbanOutfitters/52924974_070_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=540", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/52924974_070_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=540", desc: "Elegant vanity that makes for a standout getting-ready space to up the glamor. Table features tubular metal framing in a looping design with a tempered glass tabletop and built-in round mirror. This custom furniture piece will be made to order just for you. 2 people recommended for assembly.", subtype: "Furniture")
Product.create(name: "Faux Leather Rocking Chair",price: 220, color: "Grey", category: "home", image: "https://images.urbndata.com/is/image/UrbanOutfitters/65314858_004_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=540", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/65314858_004_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=540", desc: "A modern take on the perfect spot for curling up with a good book, this faux leather rocking chair has a sleekly minimalist profile. Topped with fixed cushions upholstered in faux leather, it’s supported by a powder-coated metal frame and engineered wood detailing at the armrests and rocking base. Assembly required.", subtype: "Furniture")
Product.create(name: "Metal Storage Ladder",price: 99, color: "Black", category: "home", image: "https://images.urbndata.com/is/image/UrbanOutfitters/66372574_001_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=540", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/66372574_001_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=540", desc: "Perfect for organizing in small spaces, this tall storage ladder has six fixed rungs to help you elevate your stuff.", subtype: "Living")
Product.create(name: "Cast Iron Fire Pit",price: 99, color: "Black", category: "home", image: "https://images.urbndata.com/is/image/UrbanOutfitters/59820993_001_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=540", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/59820993_001_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=540", desc: "Lightweight cast iron fire pit by Sunnydaze Decor with a modern standing silhouette that’s perfect for making the most of summer nights.", subtype: "Living")
Product.create(name: "Low Lounge Chair",price: 350, color: "Grey", category: "home", image: "https://images.urbndata.com/is/image/UrbanOutfitters/65356172_004_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=540", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/65356172_004_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=540", desc: "Modern lounge chair with all-over woven upholstery and a cushioned construction that makes the curving profile so comfy. Topped with tucked seaming for a textural interpretation that adds an effortlessly cool dimension to your space. No assembly required - just unfold and enjoy!", subtype: "Furniture")
Product.create(name: "Mona Lisa Poster",price: 8, color: "Multi", category: "home", image: "https://images.urbndata.com/is/image/UrbanOutfitters/64601933_095_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=540", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/64601933_095_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=540", desc: "Display the perennial mystique of Mona Lisa with this poster reproduction of DaVinci’s masterpiece.", subtype: "Decor")
Product.create(name: "Bed Canopy",price: 85, color: "White", category: "home", image: "https://images.urbndata.com/is/image/UrbanOutfitters/55639702_010_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=540", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/55639702_010_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=540", desc: "Create a sanctuary space that’s all your own with this woven textile canopy, designed to be suspended from the ceiling or tied to a compatible four poster bed frame. Adjustable ties add a ruched, draped look that’s crisp and femme.", subtype: "Bedding")
Product.create(name: "Janna Duvet Cover",price: 99, color: "Multi", category: "home", image: "https://images.urbndata.com/is/image/UrbanOutfitters/63050991_011_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=540", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/63050991_011_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=540", desc: "Taking cues from the bohemian motifs of vintage scarves, this duvet cover features panes of ditsy designs and paisley prints separated by a grid of florals. Made from a soft cotton slub weave, it comes equipped with ties at the interior corners to hold your duvet insert secure, topped with a hidden-button closure to easily remove on wash day. Shams and duvet insert sold separately.", subtype: "Bedding")
Product.create(name: "Modern L-Shaped Desk",price: 285, color: "Brown", category: "home", image: "https://images.urbndata.com/is/image/UrbanOutfitters/65195281_020_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=540", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/65195281_020_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=540", desc: "Curate an expansive workspace that’s equally modern and serene with this L-shaped desk. Featuring a contrasting finish with metal framing and engineered wood desktop and storage, including two drawers with roller extension glides and a shelf, perfect for holding art supplies, files and more. Two people recommended for assembly.", subtype: "Furniture")
Product.create(name: "Wire Wall Grid",price: 65, color: "Silver", category: "home", image: "https://images.urbndata.com/is/image/UrbanOutfitters/65116378_007_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=540", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/65116378_007_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=540", desc: "Maximize your storage and curate an ultra-efficient, sleekly modern workspace with this wire wall grid. Mounts to wall and comes with accessories including a basket, shelf, hook rack and clips for holding stationery, photos, jewelry, office supplies and more. In a polished finish. Mounts to wall; hardware included.", subtype: "Decor")
Product.create(name: "Maia Sectional Sofa", price: 1200, color: "White", category: "home", image: "https://images.urbndata.com/is/image/UrbanOutfitters/66868555_012_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=960", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/66868555_012_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=540", desc: "Modern minimal sectional sofa. Three-piece silhouette in a low profile with a comfy seat backed by tonal lumbar cushions. Two people recommended for assembly. ", subtype: "Furniture")
Product.create(name: "Cloud LED Neon Sign",price: 15, color: "Blue", category: "home", image: "https://images.urbndata.com/is/image/UrbanOutfitters/58309303_045_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=540", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/58309303_045_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=540", desc: "Send a message that your space is on cloud nine with this neon sign and message board by Brilliant Ideas. Featuring a wooden frame, made with LED tubing and slatted structure for popping in letters to set the mood in your sanctuary space. Battery powered.", subtype: "Lighting")
# Product.create(name:, price:, color:, category:"Home", image:, backimage:, desc:, quantity:1)
# Product.create(name:, price:, color:, category:"Home", image:, backimage:, desc:, quantity:1)
# Product.create(name:, price:, color:, category:"Home", image:, backimage:, desc:, quantity:1)
# Product.create(name:, price:, color:, category:"Home", image:, backimage:, desc:, quantity:1)
# Product.create(name:, price:, color:, category:"Home", image:, backimage:, desc:, quantity:1)












#LIFESTYLE 
Product.create(name: "Eco-Friendly Wheat Fiber Wireless Bluetooth Speaker", price: 18, color: "Tan", category: "lifestyle", image: "https://images.urbndata.com/is/image/UrbanOutfitters/64239601_024_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/64239601_024_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc: "Constructed with biodegradable wheat fiber, this wireless speaker by SOAR puts a sustainable spin on your soundtrack. Topped with bumper edges in a compact silhouette you can take on the go, it connects to your tech via Bluetooth and operates via buttons along the top edge. Rechargeable battery-powered.", subtype: "Music")
Product.create(name: "Dream Journal And Sticker Set", price: 12, color: "Red", category: "lifestyle", image: "https://images.urbndata.com/is/image/UrbanOutfitters/64503907_054_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=1314", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/64503907_054_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc: "Catalog your dreams with this spiralbound journal, perfect for keeping right on your nightstand. Featuring dedicated space for jotting down dreams with colorful stickers for a nostalgic touch we love", subtype: "Books")
Product.create(name: "Daisy Bluetooth Shower Speaker", price: 25, color: "White", category: "lifestyle", image: "https://images.urbndata.com/is/image/UrbanOutfitters/64184799_010_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/64184799_010_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc: "Flower-shaped speaker designed with a splashproof construction so you can listen to your favorite music and more while you scrub-a-dub. Bluetooth-enabled.", subtype: "Music")
Product.create(name: "Polaroid Now+ Instant Camera", price: 125, color: "White", category: "lifestyle", image: "https://images.urbndata.com/is/image/UrbanOutfitters/65485948_010_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/65485948_010_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc: "Capture memories in an instant and with major style with this Polaroid camera. With built-in features designed for effortless use and precise results. Autofocus, self-timer and flash ensure accurate pictures, while double exposure mode offers endless possibilities for creativity. Instant film sold separately.", subtype: "Living")
Product.create(name: "Butterfly Sticky Notepad Set", price: 9, color: "Multi", category: "lifestyle", image: "https://images.urbndata.com/is/image/UrbanOutfitters/65404683_095_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/65404683_095_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc: "Never let a stray thought flitter away - write down memos, ideas and more on these butterfly sticky notes. Featuring five little notepads in assorted colors and sizes.", subtype: "Books")
Product.create(name: "Hero Cosmetics Emergency Stress Kit", price: 14, color: "Multi", category: "lifestyle", image: "https://images.urbndata.com/is/image/UrbanOutfitters/64505829_000_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/64505829_000_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc: "Don’t let the stress of the holidays bring you down – Hero’s got your skincare covered with this step-by-step holiday gift set featuring everything you need to tackle emergency breakouts.", subtype: "Living")
Product.create(name: "Smoko Frog Heated Slipper", price: 35, color: "Green", category: "lifestyle", image: "https://images.urbndata.com/is/image/UrbanOutfitters/63641955_030_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/63641955_030_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc: "Jump into these super soft fleece slippers from Smoko that even heat up when your toes are feeling chilly", subtype: "Living")
Product.create(name: "Modern Sprout Holiday Tiny Terracotta Grow Kit", price: 16, color: "peppermint", category: "lifestyle", image: "https://images.urbndata.com/is/image/UrbanOutfitters/64271554_030_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/64271554_030_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc: "Mini grow kit featuring all the essentials - just add water and sunshine and watch your chosen plant bloom in the terracotta pot. Includes grow medium, plant food and seeds.", subtype: "Living")
Product.create(name: "The Little Book Light", price: 11, color: "Blue", category: "lifestyle", image: "https://images.urbndata.com/is/image/UrbanOutfitters/66602640_045_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/66602640_045_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc: "Small clip-on book lamp that easily adjusts to shed a little light at just the right angle.", subtype: "Books")
Product.create(name: "Rock And Roll It Roll-Up Drum Kit", price: 35, color: "Black", category: "lifestyle", image: "https://images.urbndata.com/is/image/UrbanOutfitters/65265597_001_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/65265597_001_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc: "Travel to the beat of your own drum with this flexible roll-up drum kit. Play for hours with battery and USB power options. Record & playback your beats featuring 7 drum sound styles.", subtype: "Music")
Product.create(name: "Goli Nutrition Gummy Supplement ", price: 16, color: "Orange", category: "lifestyle", image: "https://images.urbndata.com/is/image/UrbanOutfitters/55528228_080_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/55528228_080_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc: "Goli Nutrition believes that happiness and wellness go hand in hand, and has created an easy, nutritious and delicious way to incorporate wellness into their daily routine. Goli Gummies are gluten-free, gelatin-free, vegan, non-GMO and made with select organic ingredients, free from artificial sweeteners and preservatives.", subtype: "Living")
Product.create(name: "Puffy Panda Paper Clip Set", price: 4, color: "Black", category: "lifestyle", image: "https://images.urbndata.com/is/image/UrbanOutfitters/65181216_009_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/65181216_009_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc: "Clip it cutely with this set of two oversized paper clips topped with puffy panda accents. Set of 2.", subtype: "Books")
Product.create(name: "Cooluli 12L Mini Beauty Refrigerator", price: 110, color: "Pink", category: "lifestyle", image: "https://images.urbndata.com/is/image/UrbanOutfitters/64748833_066_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/64748833_066_f?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc: "Perfect for cooling your crystal roller, serums, creams and sodas, too, this mini fridge from Cooluli is an ultra-versatile addition to your space. Compact, mini design switches from heating to cooling with a thermoelectric system that adapts to your needs with quiet, low-noise operation. Features a sleek case.", subtype: "Living")
Product.create(name: "PlayStation Icon Light", price: 36, color: "White", category: "lifestyle", image: "https://images.urbndata.com/is/image/UrbanOutfitters/62785837_010_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/62785837_010_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc: "Give your gaming cave an on-theme look with this light shaped like PlayStation’s controller icons. Offers multiple lighting settings and can operate via USB or battery.", subtype: "Living")
Product.create(name: "Grass Pen Stand", price: 10, color: "Green", category: "lifestyle", image: "https://images.urbndata.com/is/image/UrbanOutfitters/58638719_030_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720" , backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/58638719_030_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc: "Treat your pen collection like little flowers when you plant them in this fake grass stand.", subtype: "Books")
Product.create(name: "Hydro Flask Packable Water Bottle Sling Bag", price: 18, color: "Blue", category: "lifestyle", image: "https://images.urbndata.com/is/image/UrbanOutfitters/63181945_040_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/63181945_040_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc: "Hydrating on the go just got so much easier thanks to this sling bag by Hydro Flask, designed to fit your go-to bottle perfectly. Made from durable nylon with an adjustable shoulder strap. Fits 32 oz and 40 oz wide mouth Hydro Flask bottles.", subtype: "Living")
Product.create(name: "Spray Bottle Watering Can", price: 16, color: "Yellow", category: "lifestyle", image: "https://images.urbndata.com/is/image/UrbanOutfitters/62997747_072_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/62997747_072_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc: "Ingeniously dual-purpose spray bottle-watering can hybrid that puts your plant hydration essentials in one convenient vessel. Equipped with both a functional spray bottle for misting and watering can for deeper hydration melded together. Topped with a handle for easy carrying.", subtype: "Living")
Product.create(name: "Crosley Voyager Bluetooth Record Player", price: 68, color: "Green", category: "lifestyle", image: "https://images.urbndata.com/is/image/UrbanOutfitters/58432089_031_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/58432089_031_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc: "Bluetooth-compatible and portable vintage-inspired turntable housed in a retro-look briefcase design from the experts at Crosley. This entry-level record player is perfect for playing your favorite vinyl LPs, and comes complete with a headphone jack, RCA audio out, and features dynamic, full-range stereo speakers.", subtype: "Music")
Product.create(name: "Hydro Flask Standard Mouth 21 oz Water Bottle", price: 24, color: "Blue", category: "lifestyle", image: "https://images.urbndata.com/is/image/UrbanOutfitters/54189493_044_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/54189493_044_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc: "With a slim, lightweight design, this 21 oz water bottle from Hydro Flask features double-walled TempShield™ insulation that keeps beverages cold for up to 24 hours and hot for up to 12 hours. Screw-top insulated sport cap lid features loop for easy toting, and slim build slips right into most cupholders and bags.", subtype: "Living")
Product.create(name: "Corduroy Backpack", price: 39, color: "Tan", category: "lifestyle", image: "https://images.urbndata.com/is/image/UrbanOutfitters/64323140_016_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/64323140_016_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc: "Everyday backpack with a textured cotton cord fabrication. Includes a spacious main compartment and additional front pocket both fitted with zip closures. Finished with a top carry handle & adjustable padded shoulder straps.", subtype: "Living")
Product.create(name: "World's Smallest Barrel of Monkeys Game", price: 8, color: "Blue", category: "lifestyle", image: "https://images.urbndata.com/is/image/UrbanOutfitters/65202657_040_m?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/65202657_040_m2?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc: "The World’s Smallest collection from Super Impulse are miniature replicas of iconic brands. These are the world’s most classic toys and games in their smallest sizes ever!", subtype: "Living")
Product.create(name: "Planter Bluetooth Speaker", price: 22, color: "White", category: "lifestyle", image: "https://images.urbndata.com/is/image/UrbanOutfitters/63452940_010_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/63452940_010_g?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc: "Make your planter pull double duty with this sleek iteration featuring an included Bluetooth speaker. Pop in your favorite plant (not included) and activate the built-in LED lights and noises with the touch of a petal. Stream your favorite tracks digitally and utilize the touch control and multicolor lights to complete the experience.", subtype: "Music")
Product.create(name: "Fjallraven Kånken Mini Backpack", price: 55, color: "Green Blue", category: "lifestyle", image: "https://images.urbndata.com/is/image/UrbanOutfitters/38957635_407_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/38957635_407_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc: "Fjällräven's classic Kånken backpack, now in a mini size perfect for festival days. Designed in 1978 and still just as relevant today with durable polyvinyl, a roomy main zip compartment and easily accessible front and side pockets. Complete with adjustable woven shoulder straps and dual top handles for easy carrying.", subtype: "Living")
Product.create(name: "Love Oracles Card Deck", price: 14, color: "Pink", category: "lifestyle", image: "https://images.urbndata.com/is/image/UrbanOutfitters/65347304_066_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/65347304_066_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc: "Full of wisdom from lovers through the ages, including everyone from Shakespeare to Elizabeth Taylor, this oracle card deck will guide your way through romantic entanglements, friendships and family trees.", subtype: "Living")
Product.create(name: "Tetris Light", price: 24, color: "Multi", category: "lifestyle", image: "https://images.urbndata.com/is/image/UrbanOutfitters/64714280_095_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/64714280_095_f?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc: "Colorful and nostalgic, this kitschy light features a stack of blocks that haven’t quite become a Tetris yet - perfect for inspiring a little competitive spirit to get your highest score yet. Illuminates with a vivid glow and three display modes including a music-reactive function. Battery-powered or USB operated.", subtype: "Living")
Product.create(name: "Thermo 14.2oz Insulated Tea & Fruit Infuser Bottle", price: 18, color: "White", category: "lifestyle", image: "https://images.urbndata.com/is/image/UrbanOutfitters/64796758_007_m?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/64796758_007_m5?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc: "The Thermo Tea & Fruit Infuser Bottle is designed to hold flavored waters, teas, and other beverages that are infused or steeped. An integrated filter keeps tea leaves, steeping herbs, and infusing fruit out of the pouring area so you achieve maximum flavor with no residue in your drink.", subtype: "Living")
# Product.create(name:, price:, color:, category:"lifestyle", image:, backimage:, desc:, quantity:1)
# Product.create(name:, price:, color:, category:"lifestyle", image:, backimage:, desc:, quantity:1)
# Product.create(name:, price:, color:, category:"lifestyle", image:, backimage:, desc:, quantity:1)
# Product.create(name:, price:, color:, category:"lifestyle", image:, backimage:, desc:, quantity:1)
# Product.create(name:, price:, color:, category:"lifestyle", image:, backimage:, desc:, quantity:1)
# Product.create(name:, price:, color:, category:"lifestyle", image:, backimage:, desc:, quantity:1)
# Product.create(name:, price:, color:, category:"lifestyle", image:, backimage:, desc:, quantity:1)
# Product.create(name:, price:, color:, category:"lifestyle", image:, backimage:, desc:, quantity:1)
# Product.create(name:, price:, color:, category:"lifestyle", image:, backimage:, desc:, quantity:1)
# Product.create(name:, price:, color:, category:"lifestyle", image:, backimage:, desc:, quantity:1)
# Product.create(name:, price:, color:, category:"lifestyle", image:, backimage:, desc:, quantity:1)
# Product.create(name:, price:, color:, category:"lifestyle", image:, backimage:, desc:, quantity:1)
# Product.create(name:, price:, color:, category:"lifestyle", image:, backimage:, desc:, quantity:1)
# Product.create(name:, price:, color:, category:"lifestyle", image:, backimage:, desc:, quantity:1)
# Product.create(name:, price:, color:, category:"lifestyle", image:, backimage:, desc:, quantity:1)
# Product.create(name:, price:, color:, category:"lifestyle", image:, backimage:, desc:, quantity:1)
# Product.create(name:, price:, color:, category:"lifestyle", image:, backimage:, desc:, quantity:1)
















#CLOTHING
Product.create(name: "Low-Rise Cargo Pant", price: 44, color: "Cream", category: "clothing", image: "https://images.urbndata.com/is/image/UrbanOutfitters/62609078_012_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/62609078_012_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc: "Bring back the early 2000’s with these low-rise cargo pants. Featuring a relaxed fit through the wide leg that falls below the ankle. Complete with cargo pocket detailing and button closure at the elastic waistband.", subtype: "Bottoms")
Product.create(name: "Colorblock Long Sleeve Tee", price: 22, color: "Gold", category: "clothing", image: "https://images.urbndata.com/is/image/UrbanOutfitters/64613367_070_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/64613367_070_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc: "A long sleeve colorblock tee. Complete with exposed seams, a subtle v-neck and a cropped fit. ", subtype: "Tops")
Product.create(name: "Pull-On Flare Pant", price: 42, color: "Multi", category: "clothing", image: "https://images.urbndata.com/is/image/UrbanOutfitters/62634464_089_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/62634464_089_f?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc: "Printed full-length flare pant from Urban Outfitters. Built in an easy pull-on design with a high rise and elastic waistband.", subtype: "Bottoms")
Product.create(name: "Cropped Flannel Shirt", price: 33, color: "Red", category: "clothing", image: "https://images.urbndata.com/is/image/UrbanOutfitters/62983416_060_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/62983416_060_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc: "Your new favorite flannel. Soft flannel button-down shirt cut in a loose, boxy fit that's cropped to the waist.", subtype: "Tops")
Product.create(name: "Cleo Mock Neck Sweater", price: 38, color: "Multi", category: "clothing", image: "https://images.urbndata.com/is/image/UrbanOutfitters/63598734_049_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/63598734_049_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc: "New favorite pullover sweater in a soft knit we love. Cropped above the waist with a mock neckline.", subtype: "Sweater")
Product.create(name: "Thea Cardigan", price: 36, color: "Orange", category: "clothing", image: "https://images.urbndata.com/is/image/UrbanOutfitters/64233190_027_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/64233190_027_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc: "Essential cardigan sweater in a fuzzy textured knit. Oversized slouchy fit with a v-neck and button front. Ribbed along the trim with dolman sleeves.", subtype: "Sweater")
Product.create(name: "Puffer Jacket", price: 115, color: "Black", category: "clothing", image: "https://images.urbndata.com/is/image/UrbanOutfitters/63471668_001_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/63471668_001_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc: "A sleek puffer jacket. This jacket hits at the hip and features a cozy hood, zip closure and elastic cuffs. Finished with a logo on the sleeve.", subtype: "Jacket")
Product.create(name: "Seamed Flare Pant", price: 46, color: "Brown", category: "clothing", image: "https://images.urbndata.com/is/image/UrbanOutfitters/61655031_020_f?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/61655031_020_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc: "High-waisted silhouette offers a seamed construction with a slim fit through the thigh and finished with a flare hem.", subtype: "Bottoms")
Product.create(name: "Henley Sweater", price: 49, color: "Cream", category: "clothing", image: "https://images.urbndata.com/is/image/UrbanOutfitters/64668635_006_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/64668635_006_f?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc: "Cut in a slouchy oversized fit. Cropped just above the waist. Finished with a button placket at the front. ", subtype: "Sweater")
Product.create(name: "Bodycon Mini Dress", price: 38, color: "Grey", category: "clothing", image: "https://images.urbndata.com/is/image/UrbanOutfitters/63865547_004_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/63865547_004_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc:"Bodycon fit with a mini skirt. Square neckline. Finished with adjustable spaghetti straps.", subtype: "Dress")
Product.create(name: "Montana Butterflies Oversized Tee", price: 28, color: "White", category: "clothing", image: "https://images.urbndata.com/is/image/UrbanOutfitters/66670191_036_m?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/66670191_036_m3?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc: "This oversized Montana t-shirt is made in the USA. The tag size is XL - it measures 26” across the chest laid flat, and it's 29' long shoulder-to-hem.", subtype: "Tops")
Product.create(name: "Feeling Bold Dress", price: 98, color: "Multi", category: "clothing", image: "https://images.urbndata.com/is/image/UrbanOutfitters/62842158_009_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/62842158_009_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc: "A high/low midi dress. Cut with a v-neck and a flowy midi skirt with a center slit. Skirt is cut a bit longer in the back. Topped with puffy long sleeves and a cutout at the back.", subtype: "Dress")
Product.create(name: "Flannel Button-Down Shirt", price: 38, color: "Blue", category: "clothing", image: "https://images.urbndata.com/is/image/UrbanOutfitters/62771738_041_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/62771738_041_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc: "The essential button-down shirt. Slouchy oversized fit with a button front and chest pocket.", subtype: "Tops")
Product.create(name: "Tunic Top", price: 39, color: "Grey", category: "clothing", image: "https://images.urbndata.com/is/image/UrbanOutfitters/62867924_004_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/62867924_004_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc: "Slouchy tunic top made from 100% cotton in a seamed construction. Fitted with dropped long sleeves, side-slit hem and a notched neckline with 3-button placket.", subtype: "Tops")
Product.create(name: "Corseted Shirt Dress", price: 59, color: "Black", category: "clothing", image: "https://images.urbndata.com/is/image/UrbanOutfitters/64280886_001_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/64280886_001_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc: "A long sleeve shirt dress with corset-inspired elements. Finished with a plunging neckline, hook and eye detailing at the front and a pointed collar. Zip closure", subtype: "Dress")
Product.create(name: "Bingo Tee", price: 22, color: "Black", category: "clothing", image: "https://images.urbndata.com/is/image/UrbanOutfitters/64929698_001_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/64929698_001_f?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc: "An essential scoopneck t-shirt. Relaxed fit. Finished with a breast pocket and split hems.", subtype: "Tops")
Product.create(name: "Recycled Squares Crew Neck Sweatshirt", price: 48, color: "Grey", category: "clothing", image: "https://images.urbndata.com/is/image/UrbanOutfitters/65543936_004_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/65543936_004_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc: "Vintage crew neck sweatshirt upcycled by Urban Renewal and featuring a square dye tech effect. Each is unique & will vary from what is pictured.", subtype: "Sweater")
Product.create(name: "Puff Sleeve V-Neck Mini Dress", price: 55, color: "Black", category: "clothing", image: "https://images.urbndata.com/is/image/UrbanOutfitters/65131054_001_f?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/65131054_001_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc: "Swiss dot mini dress complete with a plunging v-neck, oversized sheer puff sleeves and a keyhole cutout at the front.", subtype: "Dress")
Product.create(name: "Graphic Shetland Sweater", price: 89, color: "Yellow", category: "clothing", image: "https://images.urbndata.com/is/image/UrbanOutfitters/62255245_072_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/62255245_072_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc: "The ultimate wool sweater with a geometric design. Crafted entirely from Shetland wool with a zip front closure. Finished with a pointed collar and ribbed hems.", subtype: "Sweater")
Product.create(name:"Casual Top", price: 22, color: "White", category: "clothing", image: "https://images.urbndata.com/is/image/UrbanOutfitters/64122260_011_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/64122260_011_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc: "Soft and stretchy seamless bra top in a cropped tee fit complete with ringer trim.", subtype: "Tops")
Product.create(name: "Cropped Puffer Vest", price: 68, color: "Red", category: "clothing", image: "https://images.urbndata.com/is/image/UrbanOutfitters/64346240_060_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/64346240_060_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc: "Cozy quilted puffer vest with a zip front. Cropped above the waist with a cinch tie", subtype: "Jacket")
Product.create(name: "Destroyed Long Sleeve Tee", price: 38, color: "Black", category: "clothing", image: "https://images.urbndata.com/is/image/UrbanOutfitters/65543951_001_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/65543951_001_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc: "Destroyed long sleeve t-shirt. Cotton tee with ripped detailing. Each one is unique and will vary from what’s pictured.", subtype: "Tops")
Product.create(name: "Long Sleeve Mini Dress", price: 55, color: "Multi", category: "clothing", image:"https://images.urbndata.com/is/image/UrbanOutfitters/65131203_059_f?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/65131203_059_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc: "Long-sleeve mini dress with romantic details. Complete with a plunging v-neck, long puff sleeves and an open strappy back.", subtype: "Dress")
Product.create(name: "Tippy Cardigan", price: 48, color: "Brown", category: "clothing", image: "https://images.urbndata.com/is/image/UrbanOutfitters/63848923_029_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/63848923_029_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc: "A checkerboard patterned cardigan. Relaxed fit. Finished with dropped shoulders and ribbed trims.", subtype: "Sweaters")
Product.create(name: "Floral Button-Down Top", price: 39, color: "White", category: "clothing", image: "https://images.urbndata.com/is/image/UrbanOutfitters/62984000_010_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/62984000_010_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc: "A lovely button-down crop top from Glamorous with floral embroidery and puffy short sleeves. Finished with a button closure.", subtype: "Tops")
Product.create(name: "Colorblock Button-Down Shirt", price: 38, color: "Multi", category: "clothing", image: "https://images.urbndata.com/is/image/UrbanOutfitters/63136212_095_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/63136212_095_h?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc:"Oversized button-down shirt in pieced colorblock. Long, loose fit with a button front and dolman sleeves. Curved at the hem and finished with a buttoned chest pocket." , subtype: "Tops")
Product.create(name:"Cropped Flannel Shirt", price: 32, color: "Multi", category: "clothing", image: "https://images.urbndata.com/is/image/UrbanOutfitters/63834352_040_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/63834352_040_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc: "Cropped flannel shirt with a raw cut hem. Long sleeve style with a button placket to the front and tab collar. Topped with a unique plaid pattern. Each shirt is one-of-a-kind & will vary from what’s pictured.", subtype: "Tops")
Product.create(name: "Cropped Long Sleeve Tee", price: 22, color: "Grey", category: "clothing", image: "https://images.urbndata.com/is/image/UrbanOutfitters/64068711_004_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/64068711_004_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc: "Washed-soft ribbed knit top cropped above the waist with long sleeves.", subtype: "Tops")
Product.create(name: "Claudia Blouse", price: 33, color: "Black", category: "clothing", image: "https://images.urbndata.com/is/image/UrbanOutfitters/62962311_001_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/62962311_001_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc: "Cropped above the waist in a fitted smocked silhouette. Cut with a square neckline and finished with poet sleeves.", subtype: "Tops")
Product.create(name: "Tweety Bird Beach Patrol T-Shirt", price: 33, color: "White", category: "clothing", image: "https://images.urbndata.com/is/image/UrbanOutfitters/67127456_010_m?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/67127456_010_m2?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc: "Vintage Distressed Tweety Bird Beach Patrol T-Shirt White", subtype: "Tops")
Product.create(name: "Tie-Back Sweater", price: 44, color: "Yellow", category: "clothing", image: "https://images.urbndata.com/is/image/UrbanOutfitters/64462252_035_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/64462252_035_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc: "A classic ribbed turtleneck sweater with an open strappy back. Finished with an adjustable tie at the back", subtype: "Sweater")
Product.create(name: "Convertible Halter Top", price: 22, color: "Brown", category: "clothing", image: "https://images.urbndata.com/is/image/UrbanOutfitters/64496300_020_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/64496300_020_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc: "A cropped halter top with a versatile plunging neckline and adjustable halter straps. Knit with a subtle ribbed texture and finished with a cropped fit.", subtype: "Tops")
Product.create(name: "Jadey Henley Top", price: 33, color: "Tan", category: "clothing", image: "https://images.urbndata.com/is/image/UrbanOutfitters/65184350_024_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/65184350_024_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc: "A classic henley top in a thermal knit. Cut with a v-neck and a curved hem. Finished with a button placket at the front.", subtype: "Tops")
Product.create(name: "Fleece Wrap Top", price: 28, color: "White", category: "clothing", image: "https://images.urbndata.com/is/image/UrbanOutfitters/64077431_011_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/64077431_011_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc: "Brushed soft fleece top from Out From Under. Cropped above the waist in a fitted silhouette with a deep-v neckline and self-tie wrap at the front.", subtype: "Tops")
Product.create(name: "Lace-Up Long Sleeve Top", price: 28, color: "Black", category: "clothing", image: "https://images.urbndata.com/is/image/UrbanOutfitters/65615882_001_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/65615882_001_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc: "A ribbed long sleeve top. Fitted and cropped just above the waist. Topped with lace-up detailing at the front.", subtype: "Tops")
Product.create(name: "Ruched Blouse", price: 28, color: "White", category: "clothing", image: "https://images.urbndata.com/is/image/UrbanOutfitters/64094709_011_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/64094709_011_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc: "Shrunken-fit top with a collared neckline and button front. Ruched along the v-neck and finished with a cropped hem.", subtype: "Tops")
Product.create(name: "Button-Front Blouse", price: 33, color: "Black", category: "clothing", image: "https://images.urbndata.com/is/image/UrbanOutfitters/61884409_001_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/61884409_001_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc: "Gauzy button-down shirt in a loose fit. Looped button front complete with a high-notched hem.", subtype: "Tops")
Product.create(name: "Rugrats Snow Fight T-Shirt Dress", price: 28, color: "White", category: "clothing", image: "https://images.urbndata.com/is/image/UrbanOutfitters/65552424_011_g?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/65552424_011_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc:"A throwback t-shirt dress featuring the Rugrats. Wear as a t-shirt dress or an oversized graphic tee.", subtype: "Tops")
Product.create(name: "Blue Bouquet Cardigan", price: 38, color: "Multi", category: "clothing", image: "https://images.urbndata.com/is/image/UrbanOutfitters/65424574_012_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/65424574_012_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720", desc: "A sweet cardigan with embroidered flowers from Kimchi Blue. Slim fit. Cropped to the waist. Finished with oversized contrasting trim.", subtype: "Sweater")


###GiftCards:

Product.create(name: "E-Gift Card", price: nil, color: nil, category: "giftcard", image: "https://images.urbndata.com/is/image/UrbanOutfitters/40805285_000_d?$medium$&qlt=80&fit=constrain", desc: "Don’t know exactly what they want? It’s ok. We do! E-Gift Cards are the perfect last-minute gift – just choose a dollar amount, enter the recipient’s email address and we’ll do the rest. ", subtype: "Holiday", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/40805285_000_d?$medium$&qlt=80&fit=constrain")
Product.create(name: "E-Gift Card", price: nil, color: nil, category: "giftcard", image: "https://images.urbndata.com/is/image/UrbanOutfitters/26612135_015_b?$medium$&qlt=80&fit=constrain", desc: "Don’t know exactly what they want? It’s ok. We do! E-Gift Cards are the perfect last-minute gift – just choose a dollar amount, enter the recipient’s email address and we’ll do the rest. ", subtype: "Holiday", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/26612135_015_b?$medium$&qlt=80&fit=constrain")
Product.create(name: "E-Gift Card", price: nil, color: nil, category: "giftcard", image: "https://images.urbndata.com/is/image/UrbanOutfitters/34303842_000_d?$medium$&qlt=80&fit=constrain", desc: "Don’t know exactly what they want? It’s ok. We do! E-Gift Cards are the perfect last-minute gift – just choose a dollar amount, enter the recipient’s email address and we’ll do the rest. ", subtype: "Holiday", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/34303842_000_d?$medium$&qlt=80&fit=constrain")

Product.create(name: "E-Gift Card", price: nil, color: nil, category: "giftcard", image: "https://images.urbndata.com/is/image/UrbanOutfitters/26612572_019_b?$medium$&qlt=80&fit=constrain", desc: "Don’t know exactly what they want? It’s ok. We do! E-Gift Cards are the perfect last-minute gift – just choose a dollar amount, enter the recipient’s email address and we’ll do the rest. ", subtype: "Holiday",  backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/26612572_019_b?$medium$&qlt=80&fit=constrain")
Product.create(name: "E-Gift Card", price: nil, color: nil, category: "giftcard", image: "https://images.urbndata.com/is/image/UrbanOutfitters/40806036_000_d?$medium$&qlt=80&fit=constrain", desc: "Don’t know exactly what they want? It’s ok. We do! E-Gift Cards are the perfect last-minute gift – just choose a dollar amount, enter the recipient’s email address and we’ll do the rest. ", subtype: "Holiday", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/40806036_000_d?$medium$&qlt=80&fit=constrain")

Product.create(name: "E-Gift Card", price: nil, color: nil, category: "giftcard", image: "https://images.urbndata.com/is/image/UrbanOutfitters/40805285_000_d?$medium$&qlt=80&fit=constrain", desc: "Don’t know exactly what they want? It’s ok. We do! E-Gift Cards are the perfect last-minute gift – just choose a dollar amount, enter the recipient’s email address and we’ll do the rest. ", subtype: "Holiday", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/40805285_000_d?$medium$&qlt=80&fit=constrain")
Product.create(name: "E-Gift Card", price: nil, color: nil, category: "giftcard", image: "https://images.urbndata.com/is/image/UrbanOutfitters/26612135_015_b?$medium$&qlt=80&fit=constrain", desc: "Don’t know exactly what they want? It’s ok. We do! E-Gift Cards are the perfect last-minute gift – just choose a dollar amount, enter the recipient’s email address and we’ll do the rest. ", subtype: "Holiday", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/26612135_015_b?$medium$&qlt=80&fit=constrain")
Product.create(name: "E-Gift Card", price: nil, color: nil, category: "giftcard", image: "https://images.urbndata.com/is/image/UrbanOutfitters/34303842_000_d?$medium$&qlt=80&fit=constrain", desc: "Don’t know exactly what they want? It’s ok. We do! E-Gift Cards are the perfect last-minute gift – just choose a dollar amount, enter the recipient’s email address and we’ll do the rest. ", subtype: "Holiday", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/34303842_000_d?$medium$&qlt=80&fit=constrain")

Product.create(name: "E-Gift Card", price: nil, color: nil, category: "giftcard", image: "https://images.urbndata.com/is/image/UrbanOutfitters/26612572_019_b?$medium$&qlt=80&fit=constrain", desc: "Don’t know exactly what they want? It’s ok. We do! E-Gift Cards are the perfect last-minute gift – just choose a dollar amount, enter the recipient’s email address and we’ll do the rest. ", subtype: "Holiday",  backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/26612572_019_b?$medium$&qlt=80&fit=constrain")
Product.create(name: "E-Gift Card", price: nil, color: nil, category: "giftcard", image: "https://images.urbndata.com/is/image/UrbanOutfitters/40806036_000_d?$medium$&qlt=80&fit=constrain", desc: "Don’t know exactly what they want? It’s ok. We do! E-Gift Cards are the perfect last-minute gift – just choose a dollar amount, enter the recipient’s email address and we’ll do the rest. ", subtype: "Holiday", backimage: "https://images.urbndata.com/is/image/UrbanOutfitters/40806036_000_d?$medium$&qlt=80&fit=constrain")